apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hml-senac-agente-orquestrador
  namespace: hml-senac-orquestrator-chatbotx
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: us.icr.io/code-engine-senac-dev/senac-wxorchestrate-multiagent:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
